services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - .env
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3030:3030"
    networks:
      - NodeRabbitMqWorker
    command: ${COMMAND}

  worker:
    build:
      context: worker
      dockerfile: Dockerfile
    container_name: worker
    env_file:
      - .env
    volumes:
      - ./worker:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3031:3031"
    networks:
      - NodeRabbitMqWorker
    command: ${COMMAND}


networks:
  NodeRabbitMqWorker:

